import { jsPDF } from "jspdf";
import { GeneratedImage } from "../types";

const generateDoc = (childName: string, theme: string, images: GeneratedImage[]) => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // --- Cover Page ---
  
  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(40);
  doc.setTextColor(0, 0, 0);
  doc.text("Coloring Book", pageWidth / 2, 40, { align: "center" });

  // Add illustration (Use the first generated image as the cover art)
  const coverImage = images.find(img => img.url);
  if (coverImage) {
    const imgWidth = 100;
    // Assuming 3:4 aspect ratio for the generated images
    const imgHeight = (imgWidth * 4) / 3; 
    const x = (pageWidth - imgWidth) / 2;
    const y = 55;
    
    try {
      doc.addImage(coverImage.url, "PNG", x, y, imgWidth, imgHeight, undefined, 'FAST');
      
      // Draw a simple decorative frame around the image
      doc.setLineWidth(1);
      doc.setDrawColor(50, 50, 50);
      doc.rect(x - 2, y - 2, imgWidth + 4, imgHeight + 4);
    } catch (e) {
      console.warn("Could not add cover image", e);
    }
  }
  
  // Child's Name
  doc.setFontSize(24);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  doc.text(`For ${childName}`, pageWidth / 2, 210, { align: "center" });
  
  // Theme
  doc.setFontSize(16);
  doc.setTextColor(100);
  doc.text(`Theme: ${theme}`, pageWidth / 2, 225, { align: "center" });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("Generated by ColorCraft", pageWidth / 2, pageHeight - 15, { align: "center" });

  // --- Content Pages ---
  for (const img of images) {
    if (!img.url) continue;

    doc.addPage();
    
    // Maintain aspect ratio or fit to page margin
    const margin = 10;
    const maxImgWidth = pageWidth - (margin * 2);
    const maxImgHeight = pageHeight - (margin * 2);
    
    try {
      // Add image
      // Note: Assuming generated images are roughly 3:4. 
      // We fit them nicely within margins.
      doc.addImage(img.url, "PNG", margin, margin, maxImgWidth, maxImgHeight, undefined, 'FAST');
    } catch (e) {
      console.warn("Could not add page image", e);
      doc.setFontSize(12);
      doc.setTextColor(200, 50, 50);
      doc.text("Image could not be loaded.", pageWidth / 2, pageHeight / 2, { align: "center" });
    }
    
    // Optional footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`ColorCraft - ${childName}'s Book`, pageWidth / 2, pageHeight - 5, { align: "center" });
  }
  
  return doc;
};

export const createColoringBookPDF = async (childName: string, theme: string, images: GeneratedImage[]) => {
  const doc = generateDoc(childName, theme, images);
  doc.save(`${childName.replace(/\s+/g, '_')}_Coloring_Book.pdf`);
};

export const printColoringBookPDF = (childName: string, theme: string, images: GeneratedImage[]) => {
  const doc = generateDoc(childName, theme, images);
  doc.autoPrint();
  window.open(doc.output('bloburl'), '_blank');
};
