import { jsPDF } from "jspdf";
import { GeneratedImage } from "../types";

// Helper to ensure image is a valid JPEG Data URI that jsPDF can handle
const processImageForPDF = (url: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "Anonymous"; // Handle CORS for remote images
    img.src = url;
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        reject(new Error("Could not get canvas context"));
        return;
      }
      // Draw white background (transparency in JPEG turns black otherwise)
      ctx.fillStyle = "#FFFFFF";
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(img, 0, 0);
      resolve(canvas.toDataURL('image/jpeg', 0.9));
    };
    img.onerror = (e) => {
      console.warn("Failed to load image for PDF processing", e);
      reject(e);
    };
  });
};

const generateDoc = (childName: string, theme: string, imagesData: string[]) => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // --- Cover Page ---

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(40);
  doc.setTextColor(0, 0, 0);
  doc.text("Coloring Book", pageWidth / 2, 40, { align: "center" });

  // Add illustration (Use the first generated image as the cover art)
  const coverImage = imagesData[0];
  if (coverImage) {
    const imgWidth = 100;
    // Assuming 3:4 aspect ratio for the generated images
    const imgHeight = (imgWidth * 4) / 3;
    const x = (pageWidth - imgWidth) / 2;
    const y = 55;

    try {
      doc.addImage(coverImage, "JPEG", x, y, imgWidth, imgHeight, undefined, 'FAST');

      // Draw a simple decorative frame around the image
      doc.setLineWidth(1);
      doc.setDrawColor(50, 50, 50);
      doc.rect(x - 2, y - 2, imgWidth + 4, imgHeight + 4);
    } catch (e) {
      console.warn("Could not add cover image", e);
    }
  }

  // Child's Name
  doc.setFontSize(24);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  doc.text(`For ${childName}`, pageWidth / 2, 210, { align: "center" });

  // Theme
  doc.setFontSize(16);
  doc.setTextColor(100);
  doc.text(`Theme: ${theme}`, pageWidth / 2, 225, { align: "center" });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("Generated by KiddoDraw", pageWidth / 2, pageHeight - 15, { align: "center" });

  // --- Content Pages ---
  for (const imgData of imagesData) {
    doc.addPage();

    // Maintain aspect ratio or fit to page margin
    const margin = 10;
    const maxImgWidth = pageWidth - (margin * 2);
    const maxImgHeight = pageHeight - (margin * 2);

    try {
      // Add image
      doc.addImage(imgData, "JPEG", margin, margin, maxImgWidth, maxImgHeight, undefined, 'FAST');
    } catch (e) {
      console.warn("Could not add page image", e);
      doc.setFontSize(12);
      doc.setTextColor(200, 50, 50);
      doc.text("Image could not be loaded.", pageWidth / 2, pageHeight / 2, { align: "center" });
    }

    // Optional footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`KiddoDraw - ${childName}'s Book`, pageWidth / 2, pageHeight - 5, { align: "center" });
  }

  return doc;
};

export const createColoringBookPDF = async (childName: string, theme: string, images: GeneratedImage[]) => {
  // Process all images first
  const validImages = images.filter(img => img.url && !img.loading && !img.error);
  const processedImages = await Promise.all(
    validImages.map(img => processImageForPDF(img.url).catch(() => null))
  );

  const validProcessed = processedImages.filter(url => url !== null) as string[];

  if (validProcessed.length === 0) throw new Error("No images could be processed for PDF");

  const doc = generateDoc(childName, theme, validProcessed);
  doc.save(`${childName.replace(/\s+/g, '_')}_Coloring_Book.pdf`);
};

export const printColoringBookPDF = async (childName: string, theme: string, images: GeneratedImage[]) => {
  // Process all images first
  const validImages = images.filter(img => img.url && !img.loading && !img.error);
  const processedImages = await Promise.all(
    validImages.map(img => processImageForPDF(img.url).catch(() => null))
  );

  const validProcessed = processedImages.filter(url => url !== null) as string[];

  if (validProcessed.length === 0) return;

  const doc = generateDoc(childName, theme, validProcessed);
  doc.autoPrint();
  window.open(doc.output('bloburl'), '_blank');
};
