import React from 'react';
import { ArrowLeft, ScrollText, AlertCircle } from 'lucide-react';

interface Props {
  onBack: () => void;
}

const TermsPage: React.FC<Props> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-white animate-fade-in-up">
      {/* Header */}
      <nav className="border-b border-slate-100 bg-white/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 h-16 flex items-center">
          <button
            onClick={onBack}
            className="flex items-center gap-2 text-slate-500 hover:text-indigo-600 transition-colors font-medium"
          >
            <ArrowLeft size={20} /> Back
          </button>
          <span className="ml-auto font-bold text-xl comic-font text-slate-800">Terms of Service</span>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-4 py-12">
        <div className="text-center mb-12">
          <div className="w-16 h-16 bg-indigo-100 text-indigo-600 rounded-full flex items-center justify-center mx-auto mb-6">
            <ScrollText size={32} />
          </div>
          <h1 className="text-4xl font-bold text-slate-900 mb-4 comic-font">Terms & Conditions</h1>
          <p className="text-lg text-slate-600">Effective Date: October 2025</p>
        </div>

        <div className="prose prose-slate max-w-none space-y-10">
          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">1. Introduction</h2>
            <p className="text-slate-600 leading-relaxed">
              Welcome to KiddoDraw! These Terms of Service ("Terms") goven your use of our website and application. By accessing or using KiddoDraw, you agree to be bound by these Terms. of Service. If you disagree with any part of the terms, then you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">2. Subscriptions</h2>
            <p className="text-slate-600 leading-relaxed">
              KiddoDraw Terms of Service are billed on a subscription basis. You will be billed in advance on a recurring and periodic basis (such as monthly).
              You may cancel your subscription at any time. The cancellation will take effect the day after the last day of the current subscription period, and you will be downgraded to the Free Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">3. Generated Content</h2>
            <p className="text-slate-600 leading-relaxed">
              You own the coloring pages you color within our application. However, the initial black and white outlines generated by AI are subject to the terms of the underlying AI provider (Google Gemini).
              You are granted a license to use these images for personal, non-commercial use.
            </p>
          </section>

          <section>
            <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 flex items-start gap-4">
              <AlertCircle className="text-amber-600 flex-shrink-0 mt-1" size={24} />
              <div>
                <h3 className="font-bold text-amber-800 mb-2">4. User Conduct</h3>
                <p className="text-amber-700 text-sm">
                  You agree not to use the Service to generate content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable. We reserve the right to terminate accounts that violate this policy.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">5. Disclaimer</h2>
            <p className="text-slate-600 leading-relaxed">
              KiddoDraw and its original content, features, and functionality are owned by KiddoDraw and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.of the service.
            </p>
          </section>
        </div>
      </main>

      <footer className="bg-slate-50 border-t border-slate-200 py-12 mt-12">
        <div className="max-w-4xl mx-auto px-4 text-center text-slate-500 text-sm">
          <p>© {new Date().getFullYear()} KiddoDraw. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default TermsPage;